### ISSUE TITLE
recursive self referencing

### ISSUE THREAD

**Issue by PeterKurucz** [coveooss/json-schema-for-humans#50]
in case of recursive self referencing like this definition:

		"tree": {
		  "type": "object",
		  "properties": {
			"value": { "type": "string" },
			"branches": {
			  "type": "array",
			  "items": { "$ref": "#/definitions/tree" },
			  "minItems": 1
			}
		  },
		  "required": ["value"]

generation fails with message: RecursionError: maximum recursion depth exceeded.
Maybe self referencing should be marked specially in output and not try to generate HTML tags endlessly.

**Comment by dblanchette** [comment]
Hi @PeterKurucz ,

Are you using the option `--no-link-to-reused-ref`? With this option, there is no checking for recursion, definitions are simply rendered from following the link.

I just updated the README to clarify this point. You may also see #8 

Would you consider there is value in having the ability not to reuse definitions except when they are recursive?

**Comment by dblanchette** [comment]
Hi again,

I just released version 0.19.0 which introduces a detection of recursive definitions.

If you don't like the behavior introduced by `--no-link-to-reused-ref` (now `--config no_link_to_reused_ref`, I had a busy weekend) but still want to be able to run on schemas with recursive definitions without crashing, this is for you!

**Comment by PeterKurucz** [comment]
Hi Denis,

thanks for your answer.
Yes, switch no-link-to-reused-ref could be a solution, but I think this
option is made for something else.
First I would keep the option no-link-to-reused-ref as present now. No
change.
Second I would show the recursion differently. E.g: In case of
recursive referencing show a special text like: circular reference. A very
old solution named Docson makes it also that way.

One more idea: error handling:
In case of an unsuccessfully HTML generation would be nice to generate an
error page according to a template.
example: user defines an error template HTML with any kind of text.
error.html
generator generates A.html for  A.json in a successful case.
but generates B.html (with content of error.html) for B.json in an
unsuccessful case.
What do you mean?

Thanks!

Bye:
P


Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. júl.
18., Szo, 3:01):

**Comment by dblanchette** [comment]
@PeterKurucz 

I added a detection of circular references in version 0.19.1. since this version, a schema with a circular reference won't crash anymore even with `--config no_link_to_reused_ref`.

For the moment, the message is the same as the one for reference reuse (when using `--config link_to_reused_ref`), so I opened #55 to change the message.

Let me know what you think about #55  or anything else :)

**Comment by PeterKurucz** [comment]
Hi Denis,

- thanks for your fix! It works no fine, but jump (click on reference)
seems to be not accurate. It doesn't jump to the beginning of HTML section.
Or am I wrong?
- one more possible request: you use anchors to navigate in the HTML
document. It's right, but so it's not possible to navigate back (with back
button in browser) to an index page, where the our subpages are listed.
Would it be possible to control (enable/disable) the generation of
onclock=setAnchor()...function in configuration file? It would be nice to
have.

FYI, we are making some experiments with your generator tool, and we plan
to use it in the future.

Thanks for your support!

Bye:
P


Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. júl.
20., H, 17:42):

**Comment by dblanchette** [comment]
Hi again Peter,

Do you have any examples of a schema that exhibits the bugs in question? 

> jump (click on reference)
seems to be not accurate. It doesn't jump to the beginning of HTML section.
Or am I wrong?

The code detects circular references. The anchor link will be made to the first seen element when building the documentation. I would be curious to see an example in order to better understand what improvement could be made to make it clearer.

> you use anchors to navigate in the HTML
document. It's right, but so it's not possible to navigate back (with back
button in browser) to an index page, where the our subpages are listed.
Would it be possible to control (enable/disable) the generation of
onclock=setAnchor()...function in configuration file? It would be nice to
have.

You can navigate back to where you clicked from by using the back and next buttons. If that does not work as intended, could you provide a schema example, the options you are using and your browser information?

By an index page do you mean having a table of content? (#51) Or do you mean to split the schema in several pages?

Anyhow, I don't have any objections to make the addition of `onclick` for anchors an option in the configuration file.

Thanks for your interest in the tool :)

**Comment by PeterKurucz** [comment]
Hi Denis,

I turn myself to you again. We are still using your tool to generate HTML
files from JSON schemata, and it's very useful!
But a short remark to elements with default attribute.
If I define an element type:string with default value e.eg: "test" that
everything is working fine.
But If I try to refer to an element type:string and I want to define a
default value in using level (ref:....) (not on definition level), then It
doesn't work.

Is it the right behaviour?

Thanks for Information!

Bye:
Péter








Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. júl.
22., Sze, 17:47):

**Comment by dblanchette** [comment]
@PeterKurucz 

If I understand correctly, you have a schema defined like so:

```json
{
  "$id": "https://example.com/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "aProperty": {
      "type": "string",
      "$ref": "#/definitions/aProperty"
    }
  },
  "definitions": {
    "aProperty": {
      "type": "string"
    }
  }
}
```

This will render like so:
![chrome_YuoCeW8wcB](https://user-images.githubusercontent.com/5759247/98608450-36e1e480-22b9-11eb-8afc-0989e6fc7650.png)

But, you would want to see the following:
![chrome_SsJwiwRxos](https://user-images.githubusercontent.com/5759247/98608486-4d883b80-22b9-11eb-8105-377cf047856a.png)

Here is the JSON Schema used to generate:
```json
{
  "$id": "https://example.com/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "aProperty": {
      "$ref": "#/definitions/aProperty"
    }
  },
  "definitions": {
    "aProperty": {
      "default": "test default",
      "type": "string"
    }
  }
}
```

The official JSON Schema specification does say that elements next to `$ref` should be merged with what is referenced. See https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.section.7.7.1.1

I opened a bug here to fix that issue: #62 

Please let me know if I understood the issue you are experiencing correctly or not

Denis

**Comment by PeterKurucz** [comment]
Hi Denis,

to be sure I give an example:
this is from you:

{
  "$id": "https://example.com/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "aProperty": {
      "$ref": "#/definitions/aProperty"
    }
  },
  "definitions": {
    "aProperty": {
      "default": "test default",
      "type": "string"
    }
  }
}

It's OK, but I need the same result in following case too:

{
  "$id": "https://example.com/schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Test",
  "type": "object",
  "properties": {
    "aProperty": {
      "$ref": "#/definitions/aProperty",

      *"default": "test default",*
    }
  },
  "definitions": {
    "aProperty": {
      "type": "string"
    }
  }
}

JSON allows it, doesn't it?

Thanks!

Bye:

P




Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
10., K, 0:46):

**Comment by dblanchette** [comment]
@PeterKurucz This is fixed as of version 0.24.1 released yesterday. The 2 examples you sent renders the same.

Thank you for bringing this to my attention :)

**Comment by PeterKurucz** [comment]
Hi Denis!

thanks for your fast correction!
the following is from your installation manual:

pip install json-schema-for-humans

how can I install a specific version/tag?  Is it possible at all?
Reason: now we have a strange bug and I want to switch back to the previous
version of your tool, to be sure that the problem is located in our code.
I intsall your tool during creation of a docker image.

Thanks!

Bye:
P

Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
10., K, 15:01):

**Comment by dblanchette** [comment]
Hi again!

With pip you can use a specific version that way:
`pip install json-schema-for-humans==0.24.0`

Denis

De : PeterKurucz <notifications@github.com>
Envoyé : 10 novembre 2020 16:13
À : coveooss/json-schema-for-humans <json-schema-for-humans@noreply.github.com>
Cc : Denis Blanchette <dblanchette@coveo.com>; State change <state_change@noreply.github.com>
Objet : Re: [coveooss/json-schema-for-humans] recursive self referencing (#50)

Hi Denis!

thanks for your fast correction!
the following is from your installation manual:

pip install json-schema-for-humans

how can I install a specific version/tag? Is it possible at all?
Reason: now we have a strange bug and I want to switch back to the previous
version of your tool, to be sure that the problem is located in our code.
I intsall your tool during creation of a docker image.

Thanks!

Bye:
P

Denis Blanchette <notifications@github.com<mailto:notifications@github.com>> ezt írta (időpont: 2020. nov.
10., K, 15:01):

**Comment by PeterKurucz** [comment]
Hi Denis,

I have bad news. It is possible to generate HTMLs from our json shemata
with Tag version: 0.24.0, but this is not the case with the newest one!
Unfortunately there is no error message in log, just after long processing
time a single message: "Killed"
I would like to send you a detailed error log. Can I switch on a trace or
debug mode?

Thanks!

Bye:
P

Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
10., K, 23:23):

**Comment by dblanchette** [comment]
@PeterKurucz 
You probably don't have any error trace because there is an infinite loop. This is probably caused by a circular reference in your schema (a refers to b, which refers to c, which refers to a).

My earlier fix addressed the issue only partially, for cases where a reference was made to a parent (a refers to a/b which refers to a).

I made a new fix released in 0.24.3 which should hopefully fix this once and for all.

Let me know if that works for you!

**Comment by PeterKurucz** [comment]
Hi Denis,

I have checked out the version 0.24.3 but the result is the same. Infinite
loop -> generation of HTMLs crashed.
Do you have any idea how to fix it?

Bye:
P

Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
11., Sze, 20:50):

**Comment by dblanchette** [comment]
@PeterKurucz To better be able to help you, I would need to have a copy of the JSON schema you are using, or, at least, a simpler version of it that does exhibit the problem.

With yesterday's fix, I am able to generate documentation from a schema with circular references, so I am at a loss at finding more examples where it would not work.

I still want to get to the bottom of this and help you though :)

**Comment by PeterKurucz** [comment]
Hi Denis,

thanks for your further investigation. I'm going to deliver the requested
schema but we process a bunch of schemata in a batch. So I don't know
exactly which one is the bad one.
I have to check them out. I will inform you soon.

Bye:
P

Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
12., Cs, 15:26):

**Comment by PeterKurucz** [comment]
Hi Denis,

you can find three json files attached.
equipmentInformation.json is the main one, and catalog.json, common.json
contain the references.
in equimentInformation.json there is a circular referencing calles:
hierarchyScope. It appears in several places in the file.
Generation of HTMLs with 0.24.0 runs without any problem but it doesn't
work with 0.24.3.

Thanks for your investigation!

Bye:
P

Denis Blanchette <notifications@github.com> ezt írta (időpont: 2020. nov.
12., Cs, 15:26):

**Comment by dblanchette** [comment]
@PeterKurucz Unfortunately, Email attachments are not added to GitHub issues. Could you add them in the GitHub issue [here ](https://github.com/coveooss/json-schema-for-humans/issues/50) or send them to me at my GitHub username @ coveo dot com.

Thanks!

**Comment by bmaranville** [comment]
The attached schema is a little big, but it shows the same issue.  I am using json-schema-for-humans==0.31.0
[refl1d.schema.zip](https://github.com/coveooss/json-schema-for-humans/files/6255070/refl1d.schema.zip)

Result of running 
```
generate-schema-doc schema/refl1d.schema.json --config no_link_to_reused_ref
```
is 
```
...
File "/home/bbm/.virtualenvs/refl1d-3.8/lib/python3.8/site-packages/json_schema_for_humans/generate.py", line 485, in type_name
    name = get_type_name(self)
  File "/home/bbm/.virtualenvs/refl1d-3.8/lib/python3.8/site-packages/json_schema_for_humans/generate.py", line 1036, in get_type_name
    def _python_type_to_json_type(python_type: Type[Union[str, int, float, bool, list, dict]]) -> str:
  File "/home/bbm/.local/lib/python3.8/typing.py", line 258, in inner
    return cached(*args, **kwds)
  File "/home/bbm/.local/lib/python3.8/typing.py", line 722, in __hash__
    return hash((Union, frozenset(self.__args__)))
  File "/home/bbm/.local/lib/python3.8/typing.py", line 330, in __hash__
    return hash((self._name,))
RecursionError: maximum recursion depth exceeded while calling a Python object
```
