### ISSUE TITLE
Add support for additionalProperties

### ISSUE THREAD

**Issue by CDuncan95** [coveooss/json-schema-for-humans#54]
As well as a boolean value, `additionalProperties` can take an entire schema, to which all additional properties must conform.

I plan to contribute this myself, and have some rough code working, taking inspiration from the PR which implemented the pattern properties support.

I don't intend on adding anything specific for the simple true/false cases, but maybe I should do that at the same time for completeness? What content should be displayed in this case?

**Comment by dblanchette** [comment]
Hi @CDuncan95, thanks for your interest in the project.

I'm not sure what's the best way to display them, maybe something like:

- If `false`, add a badge saying "No other properties allowed"
- Otherwise, add a section named "Additional Properties" (in the same way that `patternProperties` is handled)
  - If `true`, the section only says "Type: object" without a description
  - Otherwise, display the schema (just calling the `content` macro in the template)

I think that would be fairly easy to implement. If you decide to do it, make sure to start on master as I made changes yesterday.

I'm open to suggestions as I am not sure this is the best way to display it.

**Comment by CDuncan95** [comment]
> * If `true`, the section only says "Type: object" without a description

I'm thinking it might be useful to have some text there along the lines of "additional properties can take any type", since just `Type: object` might make someone think it has to be an object, rather than number, string, array etc.

Otherwise that looks like a good plan; the badge would go next to `Type: Object`, I suppose.

**Comment by dblanchette** [comment]
@CDuncan95 I agree with you for adding a message like "Additional properties can have any type or value". No need for the badge I suppose.

Thanks!
